# ----------------------  Common Configs  --------------------------
base:
  base_dir: "../runs/sam/"
  tag: ''
  stage: ''
logger:
  mode: ['tb', ]
#  mode: ''
  recorder_reduction: 'mean'

training:
  save_mode: ['all', 'best', 'latest'] # ,
  batch_size : 2 # 8 for A100
  num_workers : 8
  num_epochs : 100  # epochs
  use_amp: false
  save_interval : 1
  val_check_interval: 6
  load_pretrain_model: false

  # optim:
  lr: 0.00002
  decay_step: 2000
  decay_gamma: 0.8
  weight_decay: 0.0001
  alpha: 0.99
  validation_interval: 100

  sam_checkpoint: "/home1/quanquan/code/projects/medical-guangdong/segment-anything/sam_vit_b_01ec64.pth" # 103 server
  model_type: "vit_b"

  continue_training: false
  load_optimizer: false
  breakpoint_path: "/home1/quanquan/code/projects/finetune_large/runs/sam/ddp_b9/lora3/ckpt/model_iter_360000.pth"

dataset:
  types: ['3d'] # ['3d', '2d']
  split: 'train'
  data_root_path: '/home1/quanquan/datasets/'
  dataset_list: ["pancreas"]
  data_txt_path: './datasets/dataset_list/'
  dataset2d_path: "/home1/quanquan/datasets/08_AbdomenCT-1K/"
  cache_data_path: '/home1/quanquan/datasets/cached_dataset2/'

  cache_prefix: ['6016'] # '07'
  specific_label: [2]

test:
  batch_size: 1

